elasticsearch:
  bulk_size: 100
  byte_size: 10mb
  flush_interval: 5s
  push_templates: false
  semantic_search: false
  ssl_verification: false
  urls:
  - http://es01:9200
fs:
  add_as_inner_object: false
  add_filesize: true
  attributes_support: false
  continue_on_error: false
  excludes:
  - '*/~*'
  filename_as_id: false
  follow_symlinks: false
  index_content: true
  index_folders: false
  indexed_chars: '1000000'
  json_support: false
  lang_detect: false
  ocr:
    data_path: C:\install\tails\Tesseract-OCR\tessdata
    enabled: false
    language: eng
    path: C:\install\tails\Tesseract-OCR
    pdf_strategy: auto
  raw_metadata: false
  remove_deleted: true
  store_source: false
  update_rate: 16m
  url: /home/barako/Tails2/Sample/HebDocs
  xml_support: false
name: heb
